name: publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'


jobs:
  publish-tzb-cc2652-flasher-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: ./tzb-cc2652-flasher
        push: true
        tags: ghcr.io/tube0013/tubeszb_addons/tzb-cc2652-flasher:latest

  publish-tzb-silabs-flasher-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: ./tzb-silabs-flasher
        push: true
        tags: ghcr.io/tube0013/tubeszb_addons/tzb-silabs-flasher:latest
